# Fabric Properties
# check these on https://fabricmc.net/develop
yarn_mappings=1.21.11+build.3
loader_version=0.18.4

# Mod Properties
mod_version=1.0.6
archives_base_name=headpats

# Dependencies
fabric_version=0.140.2+1.21.11

deps.cicada=0.14.3+1.21.9-1.21.10
deps.cardinal-components-api=7.3.0
deps.modmenu=17.0.0-beta.1
deps.yacl=3.8.1+1.21.11-fabric
